### ISSUE TITLE
Fails to build (even with 6.x patch) on 6.15.x

### ISSUE THREAD

**Issue by rubin55** [PhilippeBekaert/snd-hdspe#25]
I've been using this module via the [AUR dkms package here](https://aur.archlinux.org/packages/snd-hdspe-dkms)

Since upgrading the kernel to 6.15.x, the module does not build anymore, see full [make.log](https://github.com/user-attachments/files/20697708/make.log).

Error seems to be: 

```
sound/pci/hdsp/hdspe/hdspe_midi.c:203:25: error: implicit declaration of function ‘del_timer’; did you mean ‘add_timer’? [-Wimplicit-function-declaration]
  203 |                         del_timer (&hmidi->timer);
      |                         ^~~~~~~~~
      |                         add_timer
make[6]: *** [/usr/lib/modules/6.15.2-arch1-1/build/scripts/Makefile.build:203: sound/pci/hdsp/hdspe/hdspe_midi.o] Error 1
make[6]: *** Waiting for unfinished jobs....
sound/pci/hdsp/hdspe/hdspe_pcm.c:3: warning: This comment starts with '/**', but isn't a kernel-doc comment. Refer Documentation/doc-guide/kernel-doc.rst
 * hdspe_pcm.c
sound/pci/hdsp/hdspe/hdspe_pcm.c:86: warning: This comment starts with '/**', but isn't a kernel-doc comment. Refer Documentation/doc-guide/kernel-doc.rst
 * Returns true if the card is a RayDAT / AIO / AIO Pro
sound/pci/hdsp/hdspe/hdspe_hwdep.c:3: warning: This comment starts with '/**', but isn't a kernel-doc comment. Refer Documentation/doc-guide/kernel-doc.rst
 * hdspe_hwdep.c
sound/pci/hdsp/hdspe/hdspe_proc.c:3: warning: This comment starts with '/**', but isn't a kernel-doc comment. Refer Documentation/doc-guide/kernel-doc.rst
 * hdspe_proc.c
sound/pci/hdsp/hdspe/hdspe_tco.c:23: warning: expecting prototype for hdspe(). Prototype was for LTC_TIMER_FREQ() instead
sound/pci/hdsp/hdspe/hdspe_tco.c:167: warning: expecting prototype for TCO register definitions(). Prototype was for HDSPE_TCO1_TCO_lock() instead
sound/pci/hdsp/hdspe/hdspe_control.c:20: warning: Incorrect use of kernel-doc format:  * hdspe_init_autosync_tables: calculates tables needed for the
make[5]: *** [/usr/lib/modules/6.15.2-arch1-1/build/scripts/Makefile.build:461: sound/pci/hdsp/hdspe] Error 2
make[4]: *** [/usr/lib/modules/6.15.2-arch1-1/build/scripts/Makefile.build:461: sound/pci/hdsp] Error 2
make[3]: *** [/usr/lib/modules/6.15.2-arch1-1/build/Makefile:2003: .] Error 2
make[2]: *** [/usr/lib/modules/6.15.2-arch1-1/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/snd-hdspe/1.0/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.15.2-arch1-1/build'
make: *** [Makefile:17: default] Error 2

# exit code: 2
# elapsed time: 00:00:03
----------------------------------------------------------------
```

**Comment by Schroedingers-Cat** [comment]
Can you try compiling my fork? I just published a new branch `support-v6.2` over here: https://github.com/Schroedingers-Cat/snd-hdspe/tree/support-v6.2  

The issue you're having seems to be caused by a [rename of `del_timer()` to `timer_delete()`](https://lists-ec2.96boards.org/archives/list/linux-stable-mirror@lists.linaro.org/message/R23NGUHDKFGNKSWPFB55SG3LL2AMSCZZ/). While that source mentions Kernel v6.1, the first version I have been able to find it in the docs is [v6.2](https://www.kernel.org/doc/html/v6.2/driver-api/basics.html?highlight=timer_delete#c.timer_delete). I'm only finding [`del_timer()` in v6.1](https://www.kernel.org/doc/html/v6.1/driver-api/basics.html?highlight=del_timer#c.del_timer) with no `timer_delete()` so I made the driver use `timer_delete()` from v6.2 and higher.

My fork also has audio resume after standby added (tested on an AIO Pro and a MADI).  

Very sadly, Prof. Dr. Philippe Bekaert, who was the maintainer of this repo and is the author of this driver, passed away in 2022.

**Comment by rubin55** [comment]
Hi @Schroedingers-Cat, I tried your branch and am enjoying sound on 6.15.2, much appreciated. Knew about Philippe's passing, indeed a loss. Happy you seem to be taking care of a part of his legacy (snd-hdspe)!
